version: '3.9'
services:
  web:
    build: .
    container_name: web
    command: >
      bash -c "source env/bin/activate && 
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 10500:8000
